---
# phase2.yml
# downloading and installing

- name: download Couchbase package
  get_url: url="{{downloadurl}}" dest="/{{dir1}}"

- name: Extract the installation file contents to /couchbase directory
  shell: sudo su  "{{username}}" -c 'rpm2cpio /{{dir1}}/couchbase-server-enterprise-5.5.1-centos7.x86_64.rpm | (cd /{{dir1}}; cpio  --extract --make-directories --no-absolute-filenames)'

- name: Couchbase Server Installation to the Present Working Directory (PWD)
  shell:  cd /"{{dir1}}"/opt/couchbase/; sudo su "{{username}}" -c 'sh /{{dir1}}/opt/couchbase/bin/install/reloc.sh `pwd`'

- name: start the server
  shell: cd /"{{dir1}}"/opt/couchbase/; sudo su "{{username}}" -c './bin/couchbase-server \-- -noinput -detached'

- name: pause 20 seconds
  pause:
   seconds: 20

